### ISSUE TITLE
Destroy props

### ISSUE THREAD

**Issue by edeetee** [tomanded/create-and-capture#11]
Possibly allow the players to break props by shooting, or maybe a special weapon that can do that. When you destroy the prop, it could also be turned into a normal physics prop, prehaps one with no color, to show that it isn't owned by anyone anymore. Could also play into the damage, the more you hit an object, the closer it gets to grayscale.

**Comment by motsewil** [comment]
I've gone off this idea, from our playsessions we know the game is fast paced enough as it is. and if fight rounds are reasonably long a broken fort could absolutely destroy a teams game. making it frustrating to play. Closing. Reopen if you want to discuss
