### ISSUE TITLE
Advanced props

### ISSUE THREAD

**Issue by edeetee** [tomanded/create-and-capture#9]
Allow spawning of advanced props and systems, possibly even disallow freezing of props and instead force people to use physics in their bases to hold it up with ropes, etc. http://wiki.garrysmod.com/page/Category:constraint

**Comment by motsewil** [comment]
I disagree with the possibility of disallowing freezing of props as it makes the game far to complicated for beginners. Whereas keeping freezing means it's still accessible to beginners but lets advanced players have greater tactics

**Comment by motsewil** [comment]
Done some cool stuff with this. Still working on more though :)
